# Generated by Django 4.2.1 on 2023-08-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
    ]
